### ISSUE TITLE
Trello is undefined

### ISSUE THREAD

**Issue by cskiwi** [acidstudios/angular-trello#2]
hi,

When trying to instlal the provider I get the following error

```
 Uncaught ReferenceError: Trello is not defined
```

I do have to say I had to install by downloading the file. Bower is disabled here

**Comment by tavobarrientos** [comment]
Hi, sorry for the inconvenience, the documentation and example is outdated, In past version of the provider, the provider itself adds you the client.js from Trello, for this version you can add it mannually, including this script:

``` html
<script src="https://api.trello.com/1/client.js?key=substitutewithyourapplicationkey"></script>
```

**Comment by tavobarrientos** [comment]
Trello is not defined fixed.
Thank You.
