### ISSUE TITLE
Trello is undefined

### ISSUE THREAD

**Issue by nicgirault** [acidstudios/angular-trello#3]
Hi @acidstudios !

Thank you for this librairy!

I got the error "Trello is undefined" that I solved adding

<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>

<script src="https://api.trello.com/1/client.js?key=[AppKey]"></script>

on my index.html.

The best fix would be to avoid to have to add the scripts in the index.html.
An alternative solution would be to add the lines in your readme.

Or am I missing something?

Thank you

**Comment by tavobarrientos** [comment]
Hello @nicgirault!

Well, the library automatically add the trello API when is loaded.

Can you send me a screenshot of your console pls.

**Comment by nicgirault** [comment]
The screenshot does not say a lot but Trello is not defined. My analysis is the following:

My code

``` javascript
app.config(function(TrelloApiProvider) {
  return TrelloApiProvider.init({
    key: '...',
    secret: '...',
    scopes: {
      read: true,
      write: true,
      account: true
    },
    AppName: '...'
  });
});
```

is called before the 'trello' module "run" block (where you load the Trello variable). Am I right?

**Comment by tavobarrientos** [comment]
It runs before Trello API its loaded, the problem was fixed.
