### ISSUE TITLE
Impossible to get the list of boards for a user or the list of lists for a board

### ISSUE THREAD

**Issue by nicgirault** [acidstudios/angular-trello#4]
Am I right?

Would you be interested for a PR?

**Comment by tavobarrientos** [comment]
Pull Request are welcome :)

**Comment by tavobarrientos** [comment]
You can use the method **TrelloApi.Rest** to make direct calls to the API, for instance, if you want to get the list of boards of a user:

``` javascript
TrelloApi.Rest('get', 'members/someUserName/boards').then(function(response) {
    // some logic
}, function(err) {
    // some error management Logic
});
```

More info: [Trello Member API](https://developers.trello.com/advanced-reference/member)
